queue_rules:
  - name: default
    conditions: []

pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - check-success=Test on a real server (anonymous) (1.32.8.7639-fb6452ebf) # supported-version-1
      - check-success=Test on a real server (anonymous) (1.40.5.8921-836b34c27) # supported-version-2
      - check-success=Test on a real server (anonymous) (1.42.2.10156-f737b826c) # supported-version-3
      - check-success=MSRV
    actions:
      queue:
        name: default
  - name: automatic merge media_container::server::Feature enum updates
    conditions:
      - author=andrey-yantsen
      - title=Update the media_container::server::Feature enum
      - check-success=Test on a real server (anonymous) (1.32.8.7639-fb6452ebf) # supported-version-1
      - check-success=Test on a real server (anonymous) (1.40.5.8921-836b34c27) # supported-version-2
      - check-success=Test on a real server (anonymous) (1.42.2.10156-f737b826c) # supported-version-3
    actions:
      queue:
        name: default
  - name: automatic merge tested PMS releases update
    conditions:
      - author=andrey-yantsen
      - title=Update the list of tested PMS releases
      - check-success=Test on a real server (anonymous) (1.32.8.7639-fb6452ebf) # supported-version-1
      - check-success=Test on a real server (anonymous) (1.40.5.8921-836b34c27) # supported-version-2
      - check-success=Test on a real server (anonymous) (1.42.2.10156-f737b826c) # supported-version-3
    actions:
      queue:
        name: default
  - name: queue tests for approved PRs
    conditions:
      - "#approved-reviews-by>=1"
      - base=main
      - -label=S-Merge-Queued
      - -merged
    actions:
      label:
        add: ["S-Run-Protected-Tests"]
  - name: automatic merge for main when when approved
    conditions:
      - "#approved-reviews-by>=1"
      - base=main
      - check-success=MSRV
      - check-success=Test on a real server (anonymous) (1.32.8.7639-fb6452ebf) # supported-version-1
      - check-success=Test on a real server (anonymous) (1.40.5.8921-836b34c27) # supported-version-2
      - check-success=Test on a real server (anonymous) (1.42.2.10156-f737b826c) # supported-version-3
      - check-success=Test on a real server (authenticated free account) (1.32.8.7639-fb6452ebf) # supported-version-1
      - check-success=Test on a real server (authenticated free account) (1.40.5.8921-836b34c27) # supported-version-2
      - check-success=Test on a real server (authenticated free account) (1.42.2.10156-f737b826c) # supported-version-3
      - check-success=Test on a real server (authenticated plexpass account) (1.32.8.7639-fb6452ebf) # supported-version-1
      - check-success=Test on a real server (authenticated plexpass account) (1.40.5.8921-836b34c27) # supported-version-2
      - check-success=Test on a real server (authenticated plexpass account) (1.42.2.10156-f737b826c) # supported-version-3
      - check-success=Test on a real server (unclaimed, authenticated free account) (1.32.8.7639-fb6452ebf) # supported-version-1
      - check-success=Test on a real server (unclaimed, authenticated free account) (1.40.5.8921-836b34c27) # supported-version-2
      - check-success=Test on a real server (unclaimed, authenticated free account) (1.42.2.10156-f737b826c) # supported-version-3
      - check-success=Test on a real server (authenticated free account with shared from plexpass server) (1.32.8.7639-fb6452ebf) # supported-version-1
      - check-success=Test on a real server (authenticated free account with shared from plexpass server) (1.40.5.8921-836b34c27) # supported-version-2
      - check-success=Test on a real server (authenticated free account with shared from plexpass server) (1.42.2.10156-f737b826c) # supported-version-3
    actions:
      queue:
        name: default
      label:
        remove: ["S-Run-Protected-Tests"]
        add: ["S-Merge-Queued"]
