queue_rules:
  - name: default
    conditions: []

pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - check-success=Test on a real server (anonymous) (1.28.2.6151-914ddd2b3) # supported-version-1
      - check-success=Test on a real server (anonymous) (1.30.2.6563-3d4dc0cce) # supported-version-2
      - check-success=Test on a real server (anonymous) (1.32.0.6973-a787c5a8e) # supported-version-3
      - check-success=MSRV
    actions:
      queue:
        name: default
  - name: automatic merge for main when when approved
    conditions:
      - "#approved-reviews-by>=1"
      - base=main
      - check-success=MSRV
      - check-success=Test on a real server (anonymous) (1.28.2.6151-914ddd2b3) # supported-version-1
      - check-success=Test on a real server (anonymous) (1.30.2.6563-3d4dc0cce) # supported-version-2
      - check-success=Test on a real server (anonymous) (1.32.0.6973-a787c5a8e) # supported-version-3
      - check-success=Test on a real server (authenticated free account) (1.28.2.6151-914ddd2b3) # supported-version-1
      - check-success=Test on a real server (authenticated free account) (1.30.2.6563-3d4dc0cce) # supported-version-2
      - check-success=Test on a real server (authenticated free account) (1.32.0.6973-a787c5a8e) # supported-version-3
      - check-success=Test on a real server (authenticated plexpass account) (1.28.2.6151-914ddd2b3) # supported-version-1
      - check-success=Test on a real server (authenticated plexpass account) (1.30.2.6563-3d4dc0cce) # supported-version-2
      - check-success=Test on a real server (authenticated plexpass account) (1.32.0.6973-a787c5a8e) # supported-version-3
      - check-success=Test on a real server (unclaimed, authenticated free account) (1.28.2.6151-914ddd2b3) # supported-version-1
      - check-success=Test on a real server (unclaimed, authenticated free account) (1.30.2.6563-3d4dc0cce) # supported-version-2
      - check-success=Test on a real server (unclaimed, authenticated free account) (1.32.0.6973-a787c5a8e) # supported-version-3
      - check-success=Test on a real server (authenticated free account with shared from plexpass server) (1.28.2.6151-914ddd2b3) # supported-version-1
      - check-success=Test on a real server (authenticated free account with shared from plexpass server) (1.30.2.6563-3d4dc0cce) # supported-version-2
      - check-success=Test on a real server (authenticated free account with shared from plexpass server) (1.32.0.6973-a787c5a8e) # supported-version-3
    actions:
      queue:
        name: default
