queue_rules:
  - name: default
    conditions: []

pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - check-success=Test on a real server (anonymous) (1.28.0.5999-97678ded3)
    actions:
      queue:
        name: default
  - name: automatic merge for code-gen pull requests
    conditions:
      - author=andrey-yantsen
      - title=Update the media_container::server::Feature enum
      - check-success=Test on a real server (anonymous) (1.28.0.5999-97678ded3)
    actions:
      queue:
        name: default
  - name: automatic merge for main when when approved
    conditions:
      - "#approved-reviews-by>=1"
      - base=main
      - check-success=Test on a real server (anonymous) (1.28.0.5999-97678ded3)
    actions:
      queue:
        name: default
