queue_rules:
  - name: default
    conditions: []

pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - check-success=Test on a real server (anonymous) (1.27.2.5929-a806c5905) # supported-version-1
      - check-success=Test on a real server (anonymous) (1.29.2.6364-6d72b0cf6) # supported-version-2
      - check-success=Test on a real server (anonymous) (1.31.2.6810-a607d384f) # supported-version-3
      - check-success=MSRV
    actions:
      queue:
        name: default
  - name: automatic merge for main when when approved
    conditions:
      - "#approved-reviews-by>=1"
      - base=main
      - check-success=MSRV
      - check-success=Test on a real server (anonymous) (1.27.2.5929-a806c5905) # supported-version-1
      - check-success=Test on a real server (anonymous) (1.29.2.6364-6d72b0cf6) # supported-version-2
      - check-success=Test on a real server (anonymous) (1.31.2.6810-a607d384f) # supported-version-3
      - check-success=Test on a real server (authenticated free account) (1.27.2.5929-a806c5905) # supported-version-1
      - check-success=Test on a real server (authenticated free account) (1.29.2.6364-6d72b0cf6) # supported-version-2
      - check-success=Test on a real server (authenticated free account) (1.31.2.6810-a607d384f) # supported-version-3
      - check-success=Test on a real server (authenticated plexpass account) (1.27.2.5929-a806c5905) # supported-version-1
      - check-success=Test on a real server (authenticated plexpass account) (1.29.2.6364-6d72b0cf6) # supported-version-2
      - check-success=Test on a real server (authenticated plexpass account) (1.31.2.6810-a607d384f) # supported-version-3
      - check-success=Test on a real server (unclaimed, authenticated free account) (1.27.2.5929-a806c5905) # supported-version-1
      - check-success=Test on a real server (unclaimed, authenticated free account) (1.29.2.6364-6d72b0cf6) # supported-version-2
      - check-success=Test on a real server (unclaimed, authenticated free account) (1.31.2.6810-a607d384f) # supported-version-3
      - check-success=Test on a real server (authenticated free account with shared from plexpass server) (1.27.2.5929-a806c5905) # supported-version-1
      - check-success=Test on a real server (authenticated free account with shared from plexpass server) (1.29.2.6364-6d72b0cf6) # supported-version-2
      - check-success=Test on a real server (authenticated free account with shared from plexpass server) (1.31.2.6810-a607d384f) # supported-version-3
    actions:
      queue:
        name: default
