queue_rules:
  - name: default
    conditions: []

pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - check-success=Test on a real server (anonymous) (1.25.9.5721-965587f64) # supported-version-1
      - check-success=Test on a real server (anonymous) (1.27.2.5929-a806c5905) # supported-version-2
      - check-success=Test on a real server (anonymous) (1.29.1.6313-f4cdfea9c) # supported-version-3
      - check-success=MSRV
    actions:
      queue:
        name: default
  - name: automatic merge for main when when approved
    conditions:
      - "#approved-reviews-by>=1"
      - base=main
      - check-success=Test on a real server (anonymous) (1.25.9.5721-965587f64) # supported-version-1
      - check-success=Test on a real server (anonymous) (1.27.2.5929-a806c5905) # supported-version-2
      - check-success=Test on a real server (anonymous) (1.29.1.6313-f4cdfea9c) # supported-version-3
      - check-success=Test on a real server (authenticated free account) (1.25.9.5721-965587f64) # supported-version-1
      - check-success=Test on a real server (authenticated free account) (1.27.2.5929-a806c5905) # supported-version-2
      - check-success=Test on a real server (authenticated free account) (1.29.1.6313-f4cdfea9c) # supported-version-3
      - check-success=Test on a real server (authenticated plexpass account) (1.25.9.5721-965587f64) # supported-version-1
      - check-success=Test on a real server (authenticated plexpass account) (1.27.2.5929-a806c5905) # supported-version-2
      - check-success=Test on a real server (authenticated plexpass account) (1.29.1.6313-f4cdfea9c) # supported-version-3
    actions:
      queue:
        name: default
