pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - check-success=Test on a real server (anonymous) (1.27.1.5916-6b0e31a64)
    actions:
      merge:
        method: merge
  - name: automatic merge for code-gen pull requests
    conditions:
      - author=andrey-yantsen
      - or:
        - title=Update the media_container::server::Feature enum
        - title=Update the list of tested PMS releases
      - check-success=Test on a real server (anonymous) (1.27.1.5916-6b0e31a64)
    actions:
      merge:
        method: merge
  - name: automatic merge for main when when approved
    conditions:
      - "#approved-reviews-by>=1"
      - base=main
      - check-success=Test on a real server (anonymous) (1.27.1.5916-6b0e31a64)
    actions:
      merge:
        method: merge
