// This file is automatically @generated by build.rs.
// It is not intended for manual editing.

#![allow(deprecated)]

use serde::{Deserialize, Serialize};
use serde_plain::derive_display_from_serialize;
use tracing::trace_span;

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq, Eq)]
#[allow(clippy::enum_variant_names)]
#[rustfmt::skip]
pub enum Feature {
    #[serde(
        rename = "ad-countdown-timer",
        alias = "3ae06d3a-a76b-435e-8cef-2d2008610ba2"
    )]
    AdCountdownTimer,
    #[serde(
        rename = "adaptive_bitrate",
        alias = "abd37b14-706c-461f-8255-fa9563882af3"
    )]
    AdaptiveBitrate,
    #[serde(
        rename = "album-types",
        alias = "1df3cd16-faf2-4d37-8349-1fcf3713bf1d"
    )]
    AlbumTypes,
    #[serde(
        rename = "allow_dvr",
        alias = "d8810b38-ec9b-494c-8555-3df6e365dfbd"
    )]
    AllowDvr,
    #[serde(
        rename = "amazon-loop-debug",
        alias = "d1477307-4dac-4e57-9258-252e5b908693"
    )]
    AmazonLoopDebug,
    #[serde(
        rename = "Android - Dolby Vision",
        alias = "b227c158-e062-4ff1-95d8-8ed11cecafb1"
    )]
    AndroidDolbyVision,
    #[serde(
        rename = "Android - PiP",
        alias = "86da2200-58db-4d78-ba46-f146ba25906b"
    )]
    AndroidPiP,
    #[serde(
        rename = "artist-tv",
        alias = "2797e341-b062-46ed-862f-0acbba5dd522"
    )]
    ArtistTv,
    #[serde(
        rename = "auto-sub-offsets",
        alias = "d4b4e08a-9201-4c99-9a52-8f2de8ff25cd"
    )]
    AutoSubOffsets,
    #[serde(
        rename = "avod-ad-analysis",
        alias = "c987122a-a796-432f-af00-953821c127bb"
    )]
    AvodAdAnalysis,
    #[serde(
        rename = "avod-ad-loudness",
        alias = "05826f20-284b-4bcb-b45c-2367e5c0ea72"
    )]
    #[deprecated]
    AvodAdLoudness,
    #[serde(
        rename = "avod-new-media",
        alias = "e703655b-ee05-4e24-97e3-a138da62c425"
    )]
    AvodNewMedia,
    #[serde(
        rename = "blacklist_get_signin",
        alias = "bec2ba97-4b25-472b-9cfc-674f5c68c2ae"
    )]
    BlacklistGetSignin,
    #[serde(
        rename = "blacklist-subnets",
        alias = "b3b87f19-5ccd-4b14-bb62-b9d7b982392e"
    )]
    BlacklistSubnets,
    #[serde(
        rename = "boost-voices",
        alias = "c2409baa-d044-45c7-b1f4-e9e7ccd2d128"
    )]
    BoostVoices,
    #[serde(
        rename = "bypass-web-navbar-upsell-modal",
        alias = "6aaaf4fc-c55f-4042-92c8-b35f7886d249"
    )]
    BypassWebNavbarUpsellModal,
    #[serde(
        rename = "camera_upload",
        alias = "fb34e64d-cd89-47b8-8bae-a6d20c542bae"
    )]
    CameraUpload,
    #[serde(
        rename = "chromecast-music-mp",
        alias = "58829fc9-26b8-41f4-a6c0-90ea7a11ae24"
    )]
    ChromecastMusicMp,
    #[serde(
        rename = "client-non-destructive-comskip",
        alias = "6ab6677b-ad9b-444f-9ca1-b8027d05b3e1"
    )]
    ClientNonDestructiveComskip,
    #[serde(
        rename = "client-radio-stations",
        alias = "5b6190a9-77a4-477e-9fbc-c8118e35a4c1"
    )]
    ClientRadioStations,
    #[serde(
        rename = "cloud-livetv",
        alias = "dbab9396-78ff-48f5-a5ce-c76539ed1b6e"
    )]
    #[deprecated]
    CloudLivetv,
    #[serde(
        rename = "cloudflare-turnstile-required",
        alias = "b25b878c-4f60-4337-9f6b-2d97ef41d036"
    )]
    CloudflareTurnstileRequired,
    #[serde(
        rename = "cloudsync",
        alias = "65152b75-13a9-408a-bd30-dbd23a259183"
    )]
    Cloudsync,
    #[serde(
        rename = "collections",
        alias = "1417df52-986e-4e4b-8dcd-3997fbc5c976"
    )]
    Collections,
    #[serde(
        rename = "comments_and_replies_push_notifications",
        alias = "7f46bf17-fabf-4f96-99a2-cf374f6eed71"
    )]
    CommentsAndRepliesPushNotifications,
    #[serde(
        rename = "common-sense-media-ratings-premium",
        alias = "f702522e-2445-461e-a83f-fc16c1259035"
    )]
    CommonSenseMediaRatingsPremium,
    #[serde(
        rename = "community_access_plex_tv",
        alias = "3f6baa76-7488-479a-9e4f-49ff2c0d3711"
    )]
    CommunityAccessPlexTv,
    #[serde(
        rename = "community_friends_and_followers_new_followers_push",
        alias = "359796ce-d614-427f-8165-19ff62ca053a"
    )]
    CommunityFriendsAndFollowersNewFollowersPush,
    #[serde(
        rename = "community_friends_group_notifications",
        alias = "dd69b465-7eb3-4c18-a1c0-7bc0015969e8"
    )]
    CommunityFriendsGroupNotifications,
    #[serde(
        rename = "community-friendships-management",
        alias = "7bb1ed71-a0a3-4362-aa08-7c3fa7241578"
    )]
    CommunityFriendshipsManagement,
    #[serde(
        rename = "community-new-user-onboarding",
        alias = "c4704b28-4e26-460a-bf2e-2576d0c2cb77"
    )]
    CommunityNewUserOnboarding,
    #[serde(
        rename = "community-p1",
        alias = "6272ad55-9fc0-43c6-8e1a-3f0df7a3630e"
    )]
    CommunityP1,
    #[serde(
        rename = "community-p2-r1",
        alias = "31fcbe1f-0459-42cb-a15f-5084f62374d9"
    )]
    CommunityP2R1,
    #[serde(
        rename = "community-p2-r2",
        alias = "06798ab7-4fa5-4416-9db3-f313c4292f01"
    )]
    CommunityP2R2,
    #[serde(
        rename = "community-p2-r3",
        alias = "626004b8-a8b8-4fb1-9adc-8a6277f98597"
    )]
    CommunityP2R3,
    #[serde(
        rename = "community-p2-r4",
        alias = "8f47a689-aa84-408f-bf6b-00015e9413e1"
    )]
    CommunityP2R4,
    #[serde(
        rename = "community-p2-r5",
        alias = "36fdfb7c-f0c7-4da8-a167-4775e23cab7e"
    )]
    CommunityP2R5,
    #[serde(
        rename = "community-p2r5-onboarding",
        alias = "92c11c50-efed-4eb1-b3fb-0b249fbfc845"
    )]
    CommunityP2r5Onboarding,
    #[serde(
        rename = "community-p3r1-profiles",
        alias = "52a31c3c-c8d4-49c8-9f47-18158e5528d8"
    )]
    CommunityP3r1Profiles,
    #[serde(
        rename = "community-p3r1-reactions",
        alias = "ad57040a-0b38-4862-bfcf-3fe116e9767b"
    )]
    CommunityP3r1Reactions,
    #[serde(
        rename = "community-p3r1-reviews",
        alias = "e73456a8-8962-4151-8e57-3e61c78ed9d3"
    )]
    CommunityP3r1Reviews,
    #[serde(
        rename = "community-p3r1-reviews-comments",
        alias = "47c8dede-c75d-4015-8631-8fe5665638c8"
    )]
    CommunityP3r1ReviewsComments,
    #[serde(
        rename = "community-p3r1-reviews-comments-final",
        alias = "81f9b923-039c-4828-8455-14de4ffa2059"
    )]
    CommunityP3r1ReviewsCommentsFinal,
    #[serde(
        rename = "community-p3r1-reviews-creation",
        alias = "6f4f6325-7d66-405f-96f7-b89b9685473e"
    )]
    CommunityP3r1ReviewsCreation,
    #[serde(
        rename = "community-phase0",
        alias = "fc3e8322-5e6e-4f4a-9d71-728c6d5656bd"
    )]
    CommunityPhase0,
    #[serde(
        rename = "community-phase0-web",
        alias = "a852775a-2b74-4624-aaa3-3d624471a537"
    )]
    CommunityPhase0Web,
    #[serde(
        rename = "companions_sonos",
        alias = "24b4cf36-b296-4002-86b7-f1adb657e76a"
    )]
    CompanionsSonos,
    #[serde(
        rename = "conan_redirect_alpha",
        alias = "78643fe5-d192-40c7-8e93-5ccf04c0b767"
    )]
    #[deprecated]
    ConanRedirectAlpha,
    #[serde(
        rename = "conan_redirect_beta",
        alias = "bfeaee4e-965a-4d24-b163-020c3c57d936"
    )]
    #[deprecated]
    ConanRedirectBeta,
    #[serde(
        rename = "conan_redirect_nightlies",
        alias = "98872b06-2ff3-4b71-96bc-039e2ebe7adc"
    )]
    #[deprecated]
    ConanRedirectNightlies,
    #[serde(
        rename = "conan_redirect_nightly",
        alias = "7e7596aa-6e2c-41d1-a460-1e13cf0b62f2"
    )]
    #[deprecated]
    ConanRedirectNightly,
    #[serde(
        rename = "conan_redirect_public",
        alias = "b20d91ca-1b2f-45a2-a115-c1ad24c66ac5"
    )]
    #[deprecated]
    ConanRedirectPublic,
    #[serde(
        rename = "conan_redirect_qa",
        alias = "16d69c53-4c40-4821-b9f3-57ca690b2d4d"
    )]
    #[deprecated]
    ConanRedirectQa,
    #[serde(
        rename = "content_filter",
        alias = "32cc8bf5-b425-4582-a52d-71b4f1cf436b"
    )]
    ContentFilter,
    #[serde(
        rename = "create_anonymous_users",
        alias = "f6a0e423-1a83-418c-8448-a1c7105fd71a"
    )]
    CreateAnonymousUsers,
    #[serde(
        rename = "credits-markers",
        alias = "926bc176-58ca-47da-b8e3-080ed14ea6ba"
    )]
    CreditsMarkers,
    #[serde(
        rename = "CU Sunset",
        alias = "567033ef-ffee-44fb-8f90-f678077445f9"
    )]
    CuSunset,
    #[serde(
        rename = "custom-home-removal",
        alias = "849433b0-ef60-4a71-9dd9-939bc01f5362"
    )]
    CustomHomeRemoval,
    #[serde(
        rename = "disable-facebook-auth",
        alias = "00077925-6031-401b-8679-f6617ed0cec6"
    )]
    DisableFacebookAuth,
    #[serde(
        rename = "disable_home_user_friendships",
        alias = "d29f0ee0-3d3a-46c3-b582-4bc69bc17c29"
    )]
    DisableHomeUserFriendships,
    #[serde(
        rename = "disable_sharing_friendships",
        alias = "ce8f644e-87ce-4ba5-b165-fadd69778019"
    )]
    DisableSharingFriendships,
    #[serde(
        rename = "disco-director-cast-crew-updates",
        alias = "d865f64a-ca06-472d-ae01-7a444aba6251"
    )]
    DiscoDirectorCastCrewUpdates,
    #[serde(
        rename = "disco-epg-airings-on-detail-pages",
        alias = "e9cc7ec1-be5a-4727-af7b-0f107af1a07c"
    )]
    DiscoEpgAiringsOnDetailPages,
    #[serde(
        rename = "disco-native-ads-support",
        alias = "61ace69e-8397-432e-9d46-352a00263a7a"
    )]
    DiscoNativeAdsSupport,
    #[serde(
        rename = "disco-reported-issues",
        alias = "6225c337-cd26-4ff0-b864-6c6dd84c9e0d"
    )]
    DiscoReportedIssues,
    #[serde(
        rename = "discover",
        alias = "4a933f24-464d-4a6b-b372-9e4497abd361"
    )]
    Discover,
    #[serde(
        rename = "discover-genre-browsing",
        alias = "2131d3dc-56c8-45d0-acec-c4683fd9a027"
    )]
    DiscoverGenreBrowsing,
    #[serde(
        rename = "discover-managed-related-vod",
        alias = "cb0e4c75-b1cb-43e9-97ea-6b9bc66c717b"
    )]
    DiscoverManagedRelatedVod,
    #[serde(
        rename = "discover-managed-user-test",
        alias = "807d9881-a846-40c3-8d54-84fc490b7ba9"
    )]
    DiscoverManagedUserTest,
    #[serde(
        rename = "discover-services-hub",
        alias = "ba7c4a4f-a13b-4ec0-8eb2-cd0ba2fe77f8"
    )]
    DiscoverServicesHub,
    #[serde(rename = "download_certificates")]
    DownloadCertificates,
    #[serde(
        rename = "downloads-gating",
        alias = "3bfd3ccf-8c63-4dbb-8f87-9b21b402c82b"
    )]
    DownloadsGating,
    #[serde(
        rename = "drm_support",
        alias = "34e182bd-2f62-4678-a9e9-d13b3e25019d"
    )]
    DrmSupport,
    #[serde(
        rename = "dvr",
        alias = "e8230c74-0940-4b91-9e20-6571eb068086"
    )]
    Dvr,
    #[serde(
        rename = "dvr-block-unsupported-countries",
        alias = "c92d4903-bc06-4715-8ce4-4a22674abac8"
    )]
    DvrBlockUnsupportedCountries,
    #[serde(
        rename = "epg-recent-channels",
        alias = "9c982beb-c676-4d6f-a777-ff5d37ec3081"
    )]
    EpgRecentChannels,
    #[serde(
        rename = "exclude restrictions",
        alias = "6d7be725-9a96-42c7-8af4-01e735138822"
    )]
    ExcludeRestrictions,
    #[serde(
        rename = "federated-auth",
        alias = "5d819d02-5d04-4116-8eec-f49def4e2d6f"
    )]
    FederatedAuth,
    #[serde(
        rename = "friend_request_push_notifications",
        alias = "c36a6985-eee3-4400-a394-c5787fad15b5"
    )]
    FriendRequestPushNotifications,
    #[serde(
        rename = "global-continue-watching",
        alias = "4742780c-af9d-4b44-bf5b-7b27e3369aa8"
    )]
    GlobalContinueWatching,
    #[serde(
        rename = "grandfather-sync",
        alias = "7ee1495c-2798-4288-94e2-9cd98e67d441"
    )]
    GrandfatherSync,
    #[serde(
        rename = "guided-upgrade",
        alias = "c9d9b7ee-fdd9-474e-b143-5039c04e9b9b"
    )]
    GuidedUpgrade,
    #[serde(
        rename = "hardware_transcoding",
        alias = "bc8d1fca-deb0-4d0a-a6f4-12cfd681002d"
    )]
    HardwareTranscoding,
    #[serde(
        rename = "home",
        alias = "b2403ac6-4885-4971-8b96-59353fd87c72"
    )]
    Home,
    #[serde(
        rename = "HRK_enable_EUR",
        alias = "f1ac7a53-c524-4311-9a27-713562fc24fa"
    )]
    HrkEnableEur,
    #[serde(
        rename = "hwtranscode",
        alias = "84a754b0-d1ca-4433-af2d-c949bf4b4936"
    )]
    Hwtranscode,
    #[serde(
        rename = "hybrid-guide",
        alias = "c6ce2260-a19d-4fea-9f74-a52231f03924"
    )]
    HybridGuide,
    #[serde(
        rename = "imagga-v2",
        alias = "55b9f6ed-5d26-4d2d-a436-68882a9901b5"
    )]
    ImaggaV2,
    #[serde(
        rename = "increase-password-complexity",
        alias = "9e93f8a8-7ccd-4d15-99fa-76a158027660"
    )]
    IncreasePasswordComplexity,
    #[serde(
        rename = "intro-markers",
        alias = "b83c8dc9-5a01-4b7a-a7c9-5870c8a6e21b"
    )]
    IntroMarkers,
    #[serde(
        rename = "ios14-privacy-banner",
        alias = "39dbdd84-8339-4736-96a1-0eb105cc2e08"
    )]
    Ios14PrivacyBanner,
    #[serde(
        rename = "item_clusters",
        alias = "b58d7f28-7b4a-49bb-97a7-152645505f28"
    )]
    ItemClusters,
    #[serde(
        rename = "iterable-notification-tokens",
        alias = "81c8d5fa-8d90-4833-aa10-a31a51310e2f"
    )]
    IterableNotificationTokens,
    #[serde(
        rename = "join-discover-together",
        alias = "f8f68869-07a5-4fc3-9359-d0b5ba9c487c"
    )]
    #[deprecated]
    JoinDiscoverTogether,
    #[serde(
        rename = "join-discover-together-as-friend",
        alias = "af866200-1116-4502-be15-f71457ce9d27"
    )]
    #[deprecated]
    JoinDiscoverTogetherAsFriend,
    #[serde(
        rename = "keep-payment-method",
        alias = "e4a9fd6f-4105-476b-bc57-adccd009323b"
    )]
    KeepPaymentMethod,
    #[serde(
        rename = "kevin-bacon",
        alias = "c7ae6f8f-05e6-48bb-9024-c05c1dc3c43e"
    )]
    KevinBacon,
    #[serde(
        rename = "korea-consent",
        alias = "cb151c05-1943-408a-b37c-06f7d409d6bb"
    )]
    #[deprecated]
    KoreaConsent,
    #[serde(
        rename = "le_isrg_root_x1",
        alias = "af291e9e-813f-4467-8779-5d215abc3b5f"
    )]
    LeIsrgRootX1,
    #[serde(
        rename = "lets_encrypt",
        alias = "8536058d-e1dd-4ae7-b30f-e8b059b7cc17"
    )]
    LetsEncrypt,
    #[serde(
        rename = "lightning-dvr-pivot",
        alias = "6b85840c-d79d-40c2-8d8f-dfc0b7d26776"
    )]
    LightningDvrPivot,
    #[serde(
        rename = "live-tv-channels-grid",
        alias = "9eaa5152-320b-48e6-9d47-9492ba5e5b54"
    )]
    LiveTvChannelsGrid,
    #[serde(
        rename = "live-tv-grid-pagination",
        alias = "d1b1e233-a891-45e5-935c-6114e905dbe8"
    )]
    LiveTvGridPagination,
    #[serde(
        rename = "live-tv-on-plex-subtitles",
        alias = "0b8bf267-1acf-4f89-99eb-4afbb9d250e5"
    )]
    LiveTvOnPlexSubtitles,
    #[serde(
        rename = "live-tv-support-incomplete-segments",
        alias = "dab501df-5d99-48ef-afc2-3e839e4ddc9a"
    )]
    LiveTvSupportIncompleteSegments,
    #[serde(
        rename = "livetv",
        alias = "65685ff8-4375-4e4c-a806-ec1f0b4a8b7f"
    )]
    Livetv,
    #[serde(
        rename = "livetv-platform-specific",
        alias = "de789b83-9c5e-4472-bccf-791c69e67500"
    )]
    LivetvPlatformSpecific,
    #[serde(rename = "loudness")]
    Loudness,
    #[serde(
        rename = "lyrics",
        alias = "002c9f1a-2fc0-4812-b85b-0e6140f21a0f"
    )]
    Lyrics,
    #[serde(
        rename = "media-access-split-2",
        alias = "7ab197ee-1bd6-4335-8f55-db827f0110ba"
    )]
    MediaAccessSplit2,
    #[serde(
        rename = "metadata",
        alias = "f8ea4f37-c554-476a-8852-1cbd2912f3f6"
    )]
    Metadata,
    #[serde(
        rename = "metadata_search",
        alias = "22b27e12-472e-4383-92ea-2ec3976d8e72"
    )]
    MetadataSearch,
    #[serde(
        rename = "music",
        alias = "e7cea823-02e5-48c4-a501-d37b82bf132f"
    )]
    #[deprecated]
    Music,
    #[serde(
        rename = "music-analysis",
        alias = "8fd37970-6e4e-4f00-a64a-e70b52f18e94"
    )]
    MusicAnalysis,
    #[serde(
        rename = "music_preview",
        alias = "8e8dd5c8-14a4-4208-97d4-623e09191774"
    )]
    #[deprecated]
    MusicPreview,
    #[serde(
        rename = "music_videos",
        alias = "1844737f-1a87-45c3-ab20-01435959e63c"
    )]
    MusicVideos,
    #[serde(
        rename = "new_plex_pass_prices",
        alias = "de65add8-2782-4bb8-b156-e0b57a844479"
    )]
    NewPlexPassPrices,
    #[serde(
        rename = "news-provider-sunset-modal",
        alias = "b77e6744-c18d-415a-8e7c-7aac5d7a7750"
    )]
    NewsProviderSunsetModal,
    #[serde(
        rename = "nominatim",
        alias = "0de6151c-e0dd-47c8-a81e-1acb977c7f0f"
    )]
    Nominatim,
    #[serde(
        rename = "nonAnonymousAccount",
        alias = "3dd35df0-3e4a-4e74-9ba8-2baeda83a733"
    )]
    NonAnonymousAccount,
    #[serde(
        rename = "onboarding-community",
        alias = "5dc82bc9-6038-4c21-b752-bc3454773eda"
    )]
    OnboardingCommunity,
    #[serde(
        rename = "onboarding-promo-modal",
        alias = "c0179bb9-b542-4afc-914e-63163f378485"
    )]
    #[deprecated]
    OnboardingPromoModal,
    #[serde(
        rename = "optimize-server-users-endpoint",
        alias = "ddd730e1-a0a0-429f-a7d3-7c5001d24497"
    )]
    #[deprecated]
    OptimizeServerUsersEndpoint,
    #[serde(
        rename = "parental-controls",
        alias = "73d0bba4-a6ba-4114-bac3-3039c12e08fb"
    )]
    ParentalControls,
    #[serde(
        rename = "pass",
        alias = "82999dd3-a2be-482e-9f44-357879b4f603"
    )]
    Pass,
    #[serde(
        rename = "people-pages",
        alias = "f4fe27db-7292-4e13-98b6-f3ff9b5ed5fe"
    )]
    PeoplePages,
    #[serde(
        rename = "people-pages-pms",
        alias = "652968f4-d474-4e04-a1cf-2dd1eaeb488a"
    )]
    PeoplePagesPms,
    #[serde(rename = "photo_autotags")]
    PhotoAutotags,
    #[serde(
        rename = "photos-favorites",
        alias = "96cac76e-c5bc-4596-87eb-4fdfef9aaa11"
    )]
    PhotosFavorites,
    #[serde(
        rename = "photos-metadata-edition",
        alias = "2ea0e464-ea4f-4be2-97c1-ce6ed4b377dd"
    )]
    PhotosMetadataEdition,
    #[serde(
        rename = "photos-v5",
        alias = "0a348865-4f87-46dc-8bb2-f37637975724"
    )]
    #[deprecated]
    PhotosV5,
    #[serde(
        rename = "photosV6-edit",
        alias = "850f3d1e-3f38-44c1-9c0c-e3c9127b8b5a"
    )]
    PhotosV6Edit,
    #[serde(
        rename = "photosV6-tv-albums",
        alias = "3a2b0cb6-1519-4431-98e2-823c248c70eb"
    )]
    PhotosV6TvAlbums,
    #[serde(
        rename = "playback-speed",
        alias = "068f4adf-43e5-4cc6-b5a1-1243e1be4c53"
    )]
    PlaybackSpeed,
    #[serde(
        rename = "played_badges",
        alias = "02da2909-ddfd-46be-9e42-65008a79fc05"
    )]
    PlayedBadges,
    #[serde(
        rename = "plexpass_from_billing_context",
        alias = "007fb90d-2224-4d24-bd42-e87ffde13558"
    )]
    PlexpassFromBillingContext,
    #[serde(
        rename = "pms_health",
        alias = "9aea4ca5-2095-4619-9339-88c1e662fde6"
    )]
    PmsHealth,
    #[serde(
        rename = "PMS HEVC Encoding",
        alias = "0e2acda2-d70d-4df6-96e0-f63cf264d217"
    )]
    PmsHevcEncoding,
    #[serde(
        rename = "podcasts",
        alias = "1841971c-6be5-40e6-a211-7e189d767a78"
    )]
    Podcasts,
    #[serde(
        rename = "premium-dashboard",
        alias = "222020fb-1504-492d-af33-a0b80a49558a"
    )]
    PremiumDashboard,
    #[serde(
        rename = "premium_music_metadata",
        alias = "d413fb56-de7b-40e4-acd0-f3dbb7c9e104"
    )]
    PremiumMusicMetadata,
    #[serde(
        rename = "promoted-grid-channel-filters",
        alias = "a0a78867-6b26-446f-9c3f-df4edf831259"
    )]
    PromotedGridChannelFilters,
    #[serde(
        rename = "radio",
        alias = "300231e0-69aa-4dce-97f4-52d8c00e3e8c"
    )]
    Radio,
    #[serde(
        rename = "rate-limit-client-token",
        alias = "3eb2789b-200c-4a15-91d2-dedfe560953c"
    )]
    RateLimitClientToken,
    #[serde(
        rename = "reactions_push_notifications_settings",
        alias = "34ddfac9-3a76-459a-974d-591520b809dd"
    )]
    ReactionsPushNotificationsSettings,
    #[serde(
        rename = "redirect-subscription-to-account-page",
        alias = "b8298a04-46a0-4f9c-ba1b-3b85a7d9f3b9"
    )]
    RedirectSubscriptionToAccountPage,
    #[serde(
        rename = "remote-watch-pass",
        alias = "76ddd91e-8321-4916-94b6-ded8e3727a64"
    )]
    RemoteWatchPass,
    #[serde(
        rename = "remote-watch-pass-iap",
        alias = "c9adefb7-30ea-4004-977d-ad2d1bc0a8ae"
    )]
    RemoteWatchPassIap,
    #[serde(
        rename = "require-plex-nonce",
        alias = "0cce52a7-0778-4781-9a07-712370fb6b8a"
    )]
    #[deprecated]
    RequirePlexNonce,
    #[serde(
        rename = "retro-games",
        alias = "4e27cf82-9fb6-4ebe-8e10-c48bfe6fbbb6"
    )]
    #[deprecated]
    RetroGames,
    #[serde(
        rename = "retro-games-plex-tv",
        alias = "a4bc568b-477f-4f36-894b-49e19f34353f"
    )]
    #[deprecated]
    RetroGamesPlexTv,
    #[serde(
        rename = "save-to-library",
        alias = "644c4466-05fa-45e0-a478-c594cf81778f"
    )]
    SaveToLibrary,
    #[serde(
        rename = "scrobbling-service",
        alias = "ccef9d3a-537a-43d9-8161-4c7113c6e2bb"
    )]
    ScrobblingService,
    #[serde(
        rename = "scrobbling-service-plex-tv",
        alias = "7b392594-6949-4736-9894-e57a9dfe4037"
    )]
    ScrobblingServicePlexTv,
    #[serde(rename = "server-manager")]
    ServerManager,
    #[serde(
        rename = "session_bandwidth_restrictions",
        alias = "05690239-443e-43fb-bc1a-95b5d916ca63"
    )]
    SessionBandwidthRestrictions,
    #[serde(
        rename = "session_kick",
        alias = "4ca03b04-54c1-4f9f-aea2-f813ae48f317"
    )]
    SessionKick,
    #[serde(rename = "shared-radio")]
    SharedRadio,
    #[serde(
        rename = "shared_server_notification",
        alias = "64adaa4e-aa7e-457d-b385-51438216d7fe"
    )]
    SharedServerNotification,
    #[serde(
        rename = "shared_source_notification",
        alias = "6c4d66d9-729d-49dc-b70d-ab2652abf15a"
    )]
    SharedSourceNotification,
    #[serde(
        rename = "signin_notification",
        alias = "1b3a63e4-c2f4-4011-a181-2343d3a97ef7"
    )]
    SigninNotification,
    #[serde(
        rename = "signin_with_apple",
        alias = "b5874ecb-6610-47b2-8906-1b5a897acb02"
    )]
    SigninWithApple,
    #[serde(
        rename = "silence-removal",
        alias = "a6e0a154-4735-4cbb-a6ec-7a0a146c8216"
    )]
    SilenceRemoval,
    #[serde(
        rename = "singleitemsharing",
        alias = "62b1e357-5450-41d8-9b60-c7705f750849"
    )]
    Singleitemsharing,
    #[serde(
        rename = "skip-data-licensing-consent",
        alias = "e5fe743c-af51-468a-b7e2-aabf0e79030c"
    )]
    SkipDataLicensingConsent,
    #[serde(
        rename = "sleep-timer",
        alias = "c5adf9dc-af13-4a85-a24b-98de6fa2f595"
    )]
    SleepTimer,
    #[serde(
        rename = "sonos-client-feature",
        alias = "8a9471c4-13bd-435a-b5b8-4ca6e423f355"
    )]
    SonosClientFeature,
    #[serde(
        rename = "spotlight-style-hub",
        alias = "579156cf-0664-45b4-8b7b-dda400ac3e26"
    )]
    SpotlightStyleHub,
    #[serde(
        rename = "spring_serve_ad_provider",
        alias = "fec722a0-a6d4-4fbd-96dc-4ffb02b072c5"
    )]
    SpringServeAdProvider,
    #[serde(
        rename = "Subtitles on Demand",
        alias = "bb50c92f-b412-44fe-8d8a-b1684f212a44"
    )]
    SubtitlesOnDemand,
    #[serde(
        rename = "sweet-fades",
        alias = "95149521-f64b-46ea-825c-9114e56afd2c"
    )]
    SweetFades,
    #[serde(
        rename = "sync",
        alias = "9dc1df45-fb45-4be1-9ab2-eb23eb57f082"
    )]
    Sync,
    #[serde(
        rename = "Sync v3",
        alias = "67c80530-eae3-4500-a9fa-9b6947d0f6d1"
    )]
    SyncV3,
    #[serde(
        rename = "trailers",
        alias = "6380e085-02fe-43b5-8bff-380fa4f2423c"
    )]
    Trailers,
    #[serde(
        rename = "transcoder_cache",
        alias = "a3d2d5c4-46a0-436e-a2d6-80d26f32b369"
    )]
    TranscoderCache,
    #[serde(
        rename = "TREBLE-show-features",
        alias = "85ebfb7b-77fb-4afd-bb1a-2fe2fefdddbe"
    )]
    TrebleShowFeatures,
    #[serde(
        rename = "tunefind-clients",
        alias = "07f804e6-28e6-4beb-b5c3-f2aefc88b938"
    )]
    #[deprecated]
    TunefindClients,
    #[serde(
        rename = "tunefind-vod",
        alias = "50a1cfe9-dac1-4722-aee8-cc22e9758dd6"
    )]
    TunefindVod,
    #[serde(
        rename = "tuner-sharing",
        alias = "4b522f91-ae89-4f62-af9c-76f44d8ef61c"
    )]
    TunerSharing,
    #[serde(
        rename = "tvod",
        alias = "9b5a4bea-3bbe-45d2-b226-00a6ef4d8e65"
    )]
    Tvod,
    #[serde(
        rename = "tvod_playback",
        alias = "5d80b92d-4ecf-4b0b-935f-5efc907bb2c1"
    )]
    TvodPlayback,
    #[serde(
        rename = "tvod-rentals",
        alias = "362c5ba7-41e8-400d-8354-18d53868e2d3"
    )]
    TvodRentals,
    #[serde(
        rename = "tvod-wtw",
        alias = "e25d0e25-109e-4d6d-9a54-db0931af31c3"
    )]
    TvodWtw,
    #[serde(
        rename = "two-factor-authentication",
        alias = "06d14b9e-2af8-4c2b-a4a1-ea9d5c515824"
    )]
    TwoFactorAuthentication,
    #[serde(
        rename = "two-factor-authentication-clients",
        alias = "20824f5c-6dd9-4655-9970-e7701a73c02a"
    )]
    TwoFactorAuthenticationClients,
    #[serde(
        rename = "type-first",
        alias = "d14556be-ae6d-4407-89d0-b83953f4789a"
    )]
    TypeFirst,
    #[serde(
        rename = "ultrablur",
        alias = "cec2152f-321a-4c24-8c6d-c2b35a624389"
    )]
    Ultrablur,
    #[serde(
        rename = "universal-search",
        alias = "8b46de05-1f96-4278-87b3-010ba5b1e386"
    )]
    UniversalSearch,
    #[serde(
        rename = "universal-search-live-tv",
        alias = "cce9af5d-7b44-4119-a6b1-108fd0db725c"
    )]
    UniversalSearchLiveTv,
    #[serde(
        rename = "universal-search-new-quick-search",
        alias = "b6b68f84-5127-4dc9-8a7e-3a04419b5cd4"
    )]
    UniversalSearchNewQuickSearch,
    #[serde(
        rename = "universal-watchlist",
        alias = "d9528436-ee7c-42e3-ab7b-814f85ef74b4"
    )]
    UniversalWatchlist,
    #[serde(
        rename = "unsupportedtuners",
        alias = "b46d16ae-cbd6-4226-8ee9-ab2b27e5dd42"
    )]
    Unsupportedtuners,
    #[serde(
        rename = "upgrade-3ds2",
        alias = "547514ab-3284-46e5-af77-bbaff247e3fc"
    )]
    Upgrade3ds2,
    #[serde(
        rename = "user-profile-whats-new",
        alias = "90138784-37a0-4a6b-87f6-1146d6c628e6"
    )]
    #[deprecated]
    UserProfileWhatsNew,
    #[serde(
        rename = "users-and-sharing",
        alias = "096ab4b8-04d2-41f4-9602-f1d5b9e8c7cc"
    )]
    UsersAndSharing,
    #[serde(
        rename = "visualizers",
        alias = "1dd846ed-7cde-4dc5-8ef6-53d3ce8c4e9d"
    )]
    Visualizers,
    #[serde(
        rename = "vod",
        alias = "cc9bea3b-11ab-4402-a222-4958bb129cab"
    )]
    Vod,
    #[serde(
        rename = "vod_channels",
        alias = "5050545e-95c6-4a25-b94e-1fe5a5a603d0"
    )]
    VodChannels,
    #[serde(
        rename = "vod_cloudflare",
        alias = "68747f3a-ce13-46ce-9274-1e0544c9f500"
    )]
    VodCloudflare,
    #[serde(
        rename = "vod-schema",
        alias = "1b870b8e-f1a7-497c-80b2-857d45f3123f"
    )]
    VodSchema,
    #[serde(
        rename = "vod_subtitles",
        alias = "ed374ad1-1d36-4396-8794-f710011e4fed"
    )]
    VodSubtitles,
    #[serde(
        rename = "volume-leveling",
        alias = "bbf73498-4912-4d80-9560-47c4fe212cec"
    )]
    VolumeLeveling,
    #[serde(
        rename = "watch-together-20200520",
        alias = "65faa2d0-f57e-4c63-a6b6-f1baa48951b1"
    )]
    WatchTogether20200520,
    #[serde(
        rename = "watch-together-invite",
        alias = "f83450e2-759a-4de4-8b31-e4a163896d43"
    )]
    WatchTogetherInvite,
    #[serde(
        rename = "watched-badges-v3",
        alias = "236de47b-a757-4ed7-9003-507b296057b5"
    )]
    WatchedBadgesV3,
    #[serde(
        rename = "watchlist",
        alias = "f0c452ce-11e7-465f-be04-5fb0bf4bec48"
    )]
    Watchlist,
    #[serde(
        rename = "watchlist-rss",
        alias = "f0f40559-a43a-4b8f-85ef-bdb1de1a912a"
    )]
    WatchlistRss,
    #[serde(
        rename = "watchlist-source",
        alias = "edd6039a-137c-4ace-b5d5-4e111ce9690b"
    )]
    WatchlistSource,
    #[serde(
        rename = "web-desktop-gracenote-banner",
        alias = "13056a62-9bd2-47cf-aba9-bab00095fd08"
    )]
    WebDesktopGracenoteBanner,
    #[serde(
        rename = "web-desktop-live-tv-chromecast-remote-player",
        alias = "b737075d-a6c5-4e8a-8ee9-7dc72d984062"
    )]
    WebDesktopLiveTvChromecastRemotePlayer,
    #[serde(
        rename = "web-desktop-v4-dvr-setup",
        alias = "f8484f94-92a8-4ca4-9f43-e83ab3f586c7"
    )]
    WebDesktopV4DvrSetup,
    #[serde(
        rename = "web-desktop-v4-home",
        alias = "29bca3b8-e40b-4c69-b71c-f88047240f9b"
    )]
    WebDesktopV4Home,
    #[serde(
        rename = "web-desktop-v4-pre-plays",
        alias = "591895c1-8c60-4eab-8096-3594bb190257"
    )]
    WebDesktopV4PrePlays,
    #[serde(
        rename = "web-log-viewer",
        alias = "740a75d2-6dba-4317-ba68-ed3d619d4c7a"
    )]
    WebLogViewer,
    #[serde(
        rename = "web_server_dashboard",
        alias = "5e2a89ec-fb26-4234-b66e-14d37f35dff2"
    )]
    WebServerDashboard,
    #[serde(
        rename = "web-share-v2",
        alias = "73c73f05-7131-41cd-86d7-b91301684bfe"
    )]
    WebShareV2,
    #[serde(
        rename = "webhooks",
        alias = "6f82ca43-6117-4e55-ae0e-5ea3b3e99a96"
    )]
    Webhooks,
    #[serde(
        rename = "webshows",
        alias = "55e1398c-930f-41c1-bead-f5c2e471bb25"
    )]
    Webshows,
    #[serde(
        rename = "where-to-watch-clients",
        alias = "e4f02866-841f-4ceb-a30c-0a0e68fb874d"
    )]
    WhereToWatchClients,
    UnknownUuid(String),
    #[cfg(not(feature = "tests_deny_unknown_fields"))]
    #[serde(other)]
    UnknownValue,
}

impl ::std::str::FromStr for Feature {
    type Err = serde_plain::Error;
    fn from_str(s: &str) -> ::std::result::Result<Feature, Self::Err> {
        let span = trace_span!("Feature::deserialize");
        let _span_enter = span.enter();

        let result = serde_plain::from_str(s);

        #[cfg(not(feature = "tests_deny_unknown_fields"))]
        let is_unknown_value = matches!(result, Ok(Feature::UnknownValue));
        #[cfg(feature = "tests_deny_unknown_fields")]
        let is_unknown_value = result.is_err();

        if is_unknown_value
            && s.len() == 36
            && s.as_bytes()[8] == b'-'
            && s.as_bytes()[13] == b'-'
            && s.as_bytes()[18] == b'-'
            && s.as_bytes()[23] == b'-'
        {
            return Ok(Feature::UnknownUuid(s.to_string()));
        }

        result
    }
}
derive_display_from_serialize!(Feature);

#[cfg(test)]
mod test {
    use crate::media_container::server::Feature;
    use std::str::FromStr;

    #[cfg(not(feature = "tests_deny_unknown_fields"))]
    #[plex_api_test_helper::offline_test]
    fn test_unknown_feature() {
        let f = Feature::from_str("unknown_value").unwrap();
        assert_eq!(f, Feature::UnknownValue);
    }

    #[plex_api_test_helper::offline_test]
    fn test_unknown_feature_uuid() {
        let f = Feature::from_str("cc9bea3b-aaaa-bbbb-cccc-4958bb129caa").unwrap();
        assert_eq!(
            f,
            Feature::UnknownUuid("cc9bea3b-aaaa-bbbb-cccc-4958bb129caa".to_owned())
        );
    }

    #[plex_api_test_helper::offline_test]
    fn test_known_feature() {
        let f = Feature::from_str("webhooks").unwrap();
        assert_eq!(f, Feature::Webhooks);

        let f = Feature::from_str("6f82ca43-6117-4e55-ae0e-5ea3b3e99a96").unwrap();
        assert_eq!(f, Feature::Webhooks);
    }

    #[plex_api_test_helper::offline_test]
    fn test_known_deprecated_feature() {
        let f = Feature::from_str("optimize-server-users-endpoint").unwrap();
        assert_eq!(f, Feature::OptimizeServerUsersEndpoint);

        let f = Feature::from_str("ddd730e1-a0a0-429f-a7d3-7c5001d24497").unwrap();
        assert_eq!(f, Feature::OptimizeServerUsersEndpoint);
    }
}
