---
"on":
  push:
    branches: [main, staging, trying]
  pull_request:
    branches: [main]

name: Lints (nightly)
jobs:
  check_nightly:
    name: Check (nightly)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@nightly
      - name: Run cargo check
        run: cargo check

  lints_nightly:
    name: Lints (nightly)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: "rustfmt,clippy"
      - name: Run cargo fmt
        run: cargo fmt --all -- --check
      - name: Clippy with warnings
        run: cargo clippy --all-targets --all-features -- -D warnings
