---
"on":
  schedule:
    - cron: 0 0 1 * *

name: Check for new attributes
jobs:
  plex_tags:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.set-tags.outputs.tags }}
    steps:
      - uses: actions/checkout@v2
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v1.3.0
        with:
          sharedKey: cache
      - id: set-tags
        run: |
          cargo build --package xtask
          tags=$(cargo run -q --package xtask -- get-last-plex-tags)
          echo "::set-output name=tags::$tags"

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    needs: plex_tags
    strategy:
      matrix:
        plex_server_version: ${{fromJson(needs.plex_tags.outputs.tags)}}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v1.3.0
        with:
          sharedKey: cache
      - name: "Test against real server [anonymous]"
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: "--package xtask -- test --deny-unknown-fields --docker-tag ${{ matrix.plex_server_version }}"
